applications:
  myapp:
    type: 'php:8.3'
    web:
      locations:
        '/':
          root: ''
          passthru: '/index.php'

routes:
  "https://{default}/":
    type: upstream
    upstream: "myapp:http"