applications:
  myapp:
    type: 'php:8.3'
    hooks:
      build: 'composer install'

services:
  db:
    type: 'mariadb:11.4'

routes:
  'https://{default}/':
    type: upstream
    upstream: 'myapp:http'